# Generated by Django 5.1.4 on 2024-12-25 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
    ]
