# Generated by Django 5.1.4 on 2024-12-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Dalienst', max_length=255),
            preserve_default=False,
        ),
    ]
