# Generated by Django 5.1.5 on 2025-02-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default='my-first-transaction-001', help_text='The unique transaction ID from Pesapal.', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
