# Generated by Django 5.1.4 on 2025-02-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='The unique transaction ID from Pesapal.', max_length=255, null=True, unique=True),
        ),
    ]
