# Generated by Django 5.1.4 on 2025-02-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended')], default='Active', max_length=10),
        ),
    ]
