# Generated by Django 5.1.4 on 2025-02-19 11:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PesapalIPN',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reference', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('url', models.URLField(help_text='The IPN URL to be registered with Pesapal.', max_length=255)),
                ('notification_type', models.CharField(default='GET', help_text='The type of IPN notification (GET or POST).', max_length=10)),
                ('notification_id', models.CharField(blank=True, help_text='The IPN ID returned by Pesapal after registration.', max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Pesapal IPN',
                'verbose_name_plural': 'Pesapal IPNs',
                'ordering': ('-created_at',),
            },
        ),
    ]
