# Generated by Django 5.1.4 on 2025-02-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesapal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pesapalipn',
            old_name='notification_type',
            new_name='ipn_notification_type',
        ),
    ]
